#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
	if [ "$1" = "m" ]
	then
		$MTRACE_NLP -sxcwn -pearley $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
	else
		$DEBUG_NLP -sxcwn -pearley -r$1 $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
	fi
else
	$DEBUG_NLP -sxcwn -pearley $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
fi
