#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_NLP -sxwtn -pdepth-first -r$1 $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$DEBUG_NLP -sxwtn -pdepth-first $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
