#!/bin/bash
cd `dirname $0`
. paths

#!/bin/bash
cd `dirname $0`
. ./paths

if [ $# -gt 0 ]
then
$PROFILE_NLP -sxcw -pearley -r$1 $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
else
$PROFILE_NLP -sxcw -pearley $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
fi
echo \#\#\#\#\#\#\#\#\#\# > $EARLEY_PROFILE_TRACE
echo \# Earley \# >> $EARLEY_PROFILE_TRACE
echo \#\#\#\#\#\#\#\#\#\# >> $EARLEY_PROFILE_TRACE
echo >> $EARLEY_PROFILE_TRACE
gprof $PROFILE_NLP | $SIMPLIFY_TEMPLATES >> $EARLEY_PROFILE_TRACE
vi $EARLEY_PROFILE_TRACE
