#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_NLP -sxcw -pearley -estd -r$1 $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
else
$RELEASE_NLP -sxcw -pearley -estd $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
fi
