#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_NLP -sxcwn -pdepth-first -r$1 $TID_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT
else
$RELEASE_NLP -sxcwn -pdepth-first $TID_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT
fi
