#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$DEBUG_NLP -mxwt $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$DEBUG_NLP -xwt $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
