#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_NLP -l -pto-fprtn-and-breadth-first-expand $AEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
else
$DEBUG_NLP --desc -l -pto-fprtn-and-breadth-first-expand $AEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
fi
