/*
 * GRAPENLP
 *
 * Copyright (C) 2004-2008 Université de Marne-la-Vallée <javier.sastre@univ-mlv.fr>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
 *
 */

/*
 *  @author Javier Sastre
 */

#ifndef GRAPENLP_DELAF_ENTRY_FILTER_DEFAULT_WEIGHT_H
#define GRAPENLP_DELAF_ENTRY_FILTER_DEFAULT_WEIGHT_H

namespace grapenlp
{
	/*
 	 * This is the list of delaf entry filter types, ordered following their enumeration
 	 * 
 	 * TRUE_DELAF_ENTRY_FILTER,
 	 * FALSE_DELAF_ENTRY_FILTER,
 	 * UNION_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_DELAF_ENTRY_FILTER,
 	 * MANDATORY_POS_DELAF_ENTRY_FILTER,
 	 * NEGATED_MANDATORY_POS_DELAF_ENTRY_FILTER,
 	 * FORBIDDEN_PPOOSS_DELAF_ENTRY_FILTER,
 	 * NEGATED_FORBIDDEN_PPOOSS_DELAF_ENTRY_FILTER,
 	 * SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_MANDATORY_POS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_MANDATORY_POS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_MANDATORY_POS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_MANDATORY_POS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_MANDATORY_POS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_MANDATORY_POS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_MANDATORY_POS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_MANDATORY_POS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * MANDATORY_POS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_MANDATORY_POS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * MANDATORY_POS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_MANDATORY_POS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * MANDATORY_POS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_MANDATORY_POS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * FORBIDDEN_PPOOSS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_FORBIDDEN_PPOOSS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * FORBIDDEN_PPOOSS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_FORBIDDEN_PPOOSS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * FORBIDDEN_PPOOSS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_FORBIDDEN_PPOOSS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
	 *
	 * This is the list of delaf entry filter types, ordered from the less restrictive to the most one:
	 * 
 	 * FALSE_DELAF_ENTRY_FILTER (not a dico word, infinite possibilities)
 	 * TRUE_DELAF_ENTRY_FILTER (dico word, as much possibilities as words in the dico)


 	 * CANONICAL_FORM_DELAF_ENTRY_FILTER (as much possibilities as inflected forms for the specified canonical form)
 	 * MANDATORY_POS_DELAF_ENTRY_FILTER (as much possibilities as words of the specified POS)



 	 * NEGATED_CANONICAL_FORM_DELAF_ENTRY_FILTER,
 	 * NEGATED_MANDATORY_POS_DELAF_ENTRY_FILTER,
 	 * FORBIDDEN_PPOOSS_DELAF_ENTRY_FILTER,
 	 * NEGATED_FORBIDDEN_PPOOSS_DELAF_ENTRY_FILTER,
 	 * SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_MANDATORY_POS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_MANDATORY_POS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_MANDATORY_POS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_MANDATORY_POS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_MANDATORY_POS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_MANDATORY_POS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_MANDATORY_POS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_MANDATORY_POS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_FORBIDDEN_PPOOSS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * CANONICAL_FORM_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_CANONICAL_FORM_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * MANDATORY_POS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_MANDATORY_POS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * MANDATORY_POS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_MANDATORY_POS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * MANDATORY_POS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_MANDATORY_POS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * FORBIDDEN_PPOOSS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_FORBIDDEN_PPOOSS_AND_SEMANTIC_TRAITS_DELAF_ENTRY_FILTER,
 	 * FORBIDDEN_PPOOSS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_FORBIDDEN_PPOOSS_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * FORBIDDEN_PPOOSS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_FORBIDDEN_PPOOSS_AND_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
 	 * NEGATED_SEMANTIC_AND_POSSIBLE_FLEXIONAL_TRAITS_DELAF_ENTRY_FILTER,
	 *
	 * For the moment, we do not consider this filter since it is not used in the grammars:
 	 * UNION_DELAF_ENTRY_FILTER (the union of the possibilities of its filters)
 	 */


/*	template<typename Char, typename CaseNormalizer, typename Weight>
	struct delaf_entry_filter_default_weight
	{
		Weight operator() (const delaf_entry_filter<Char, CaseNormalizer> &def) const
		{
			switch (def.get_type())
			{
				case:
			}
		}
	};*/
} //namespace grapenlp

#endif /*GRAPENLP_DELAF_ENTRY_FILTER_DEFAULT_WEIGHT_H*/
