#!/bin/bash
cd `dirname $0`
. paths

cat /dev/null > ass.txt

. ass 0 15 "-n -pdepth-first" ass.txt

. ass 0 15 "-nt -pdepth-first" ass.txt

. ass 0 15 "-pdepth-first -bstd" ass.txt
. ass 0 15 "-pdepth-first -blrb-tree" ass.txt
. ass 0 15 "-pdepth-first -blrb-tree-3w" ass.txt

. ass 0 15 "-t -pdepth-first -bstd" ass.txt
. ass 0 15 "-t -pdepth-first -blrb-tree" ass.txt
. ass 0 15 "-t -pdepth-first -blrb-tree-3w" ass.txt

. ass 0 15 "-n -pbreadth-first -estd" ass.txt
. ass 0 15 "-n -pbreadth-first -elrb-tree" ass.txt
. ass 0 15 "-n -pbreadth-first -elrb-tree-3w" ass.txt

. ass 0 15 "-nt -pbreadth-first -estd" ass.txt
. ass 0 15 "-nt -pbreadth-first -elrb-tree" ass.txt
. ass 0 15 "-nt -pbreadth-first -elrb-tree-3w" ass.txt

. ass 0 15 "-pbreadth-first -estd -bstd" ass.txt
. ass 0 15 "-pbreadth-first -estd -blrb-tree" ass.txt
. ass 0 15 "-pbreadth-first -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree -bstd" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-t -pbreadth-first -estd -bstd" ass.txt
. ass 0 15 "-t -pbreadth-first -estd -blrb-tree" ass.txt
. ass 0 15 "-t -pbreadth-first -estd -blrb-tree-3w" ass.txt
