#!/bin/bash
cd `dirname $0`
. paths

. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -estd -blrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree -bstd" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -estd -bstd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -estd -blrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree -bstd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-pto-fprtn-top -estd" ass.txt
. ass 0 15 "-pto-fprtn-top -elrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-top -elrb-tree-3w" ass.txt

. ass 0 15 "-pto-fprtn-and-top-blackboard-extract -estd" ass.txt
. ass 0 15 "-pto-fprtn-and-top-blackboard-extract -elrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-top-blackboard-extract -elrb-tree-3w" ass.txt

. ass 0 15 "-t -pto-fprtn-and-top-blackboard-extract -estd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-top-blackboard-extract -elrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-top-blackboard-extract -elrb-tree-3w" ass.txt
