#!/bin/bash
cd `dirname $0`
. paths

cat /dev/null > ass.txt

#104 parsers

. ass 0 15 "-n -pdepth-first" ass.txt

. ass 0 15 "-nt -pdepth-first" ass.txt

. ass 0 15 "-pdepth-first -bstd" ass.txt
. ass 0 15 "-pdepth-first -blrb-tree" ass.txt
. ass 0 15 "-pdepth-first -blrb-tree-3w" ass.txt

. ass 0 15 "-t -pdepth-first -bstd" ass.txt
. ass 0 15 "-t -pdepth-first -blrb-tree" ass.txt
. ass 0 15 "-t -pdepth-first -blrb-tree-3w" ass.txt

. ass 0 15 "-n -pbreadth-first -estd" ass.txt
. ass 0 15 "-n -pbreadth-first -elrb-tree" ass.txt
. ass 0 15 "-n -pbreadth-first -elrb-tree-3w" ass.txt

. ass 0 15 "-nt -pbreadth-first -estd" ass.txt
. ass 0 15 "-nt -pbreadth-first -elrb-tree" ass.txt
. ass 0 15 "-nt -pbreadth-first -elrb-tree-3w" ass.txt

. ass 0 15 "-pbreadth-first -estd -bstd" ass.txt
. ass 0 15 "-pbreadth-first -estd -blrb-tree" ass.txt
. ass 0 15 "-pbreadth-first -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree -bstd" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-pbreadth-first -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-t -pbreadth-first -estd -bstd" ass.txt
. ass 0 15 "-t -pbreadth-first -estd -blrb-tree" ass.txt
. ass 0 15 "-t -pbreadth-first -estd -blrb-tree-3w" ass.txt
#26
. ass 0 15 "-t -pbreadth-first -elrb-tree -bstd" ass.txt
. ass 0 15 "-t -pbreadth-first -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-t -pbreadth-first -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-t -pbreadth-first -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-t -pbreadth-first -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-t -pbreadth-first -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-n -pearley -estd" ass.txt
. ass 0 15 "-n -pearley -elrb-tree" ass.txt
. ass 0 15 "-n -pearley -elrb-tree-3w" ass.txt

. ass 0 15 "-pearley -estd -bstd" ass.txt
. ass 0 15 "-pearley -estd -blrb-tree" ass.txt
. ass 0 15 "-pearley -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-pearley -elrb-tree -bstd" ass.txt
. ass 0 15 "-pearley -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-pearley -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-pearley -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-pearley -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-pearley -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-t -pearley -estd -bstd" ass.txt
. ass 0 15 "-t -pearley -estd -blrb-tree" ass.txt
. ass 0 15 "-t -pearley -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-t -pearley -elrb-tree -bstd" ass.txt
. ass 0 15 "-t -pearley -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-t -pearley -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-t -pearley -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-t -pearley -elrb-tree-3w -blrb-tree" ass.txt
#52
. ass 0 15 "-t -pearley -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-pto-fprtn -estd" ass.txt
. ass 0 15 "-pto-fprtn -elrb-tree" ass.txt
. ass 0 15 "-pto-fprtn -elrb-tree-3w" ass.txt

. ass 0 15 "-pto-fprtn-and-breadth-first-expand -estd -bstd" ass.txt
. ass 0 15 "-pto-fprtn-and-breadth-first-expand -estd -blrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-breadth-first-expand -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-pto-fprtn-and-breadth-first-expand -elrb-tree -bstd" ass.txt
. ass 0 15 "-pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-pto-fprtn-and-breadth-first-expand -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-t -pto-fprtn-and-breadth-first-expand -estd -bstd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-breadth-first-expand -estd -blrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-breadth-first-expand -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-t -pto-fprtn-and-breadth-first-expand -elrb-tree -bstd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-t -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-pto-fprtn-zpps -estd" ass.txt
. ass 0 15 "-pto-fprtn-zpps -elrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-zpps -elrb-tree-3w" ass.txt

. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -estd -bstd" ass.txt
#78
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -estd -blrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree -bstd" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -estd -bstd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -estd -blrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -estd -blrb-tree-3w" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree -bstd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree-3w" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -bstd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree-3w" ass.txt

. ass 0 15 "-pto-fprtn-top -estd" ass.txt
. ass 0 15 "-pto-fprtn-top -elrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-top -elrb-tree-3w" ass.txt

. ass 0 15 "-pto-fprtn-and-top-blackboard-extract -estd" ass.txt
. ass 0 15 "-pto-fprtn-and-top-blackboard-extract -elrb-tree" ass.txt
. ass 0 15 "-pto-fprtn-and-top-blackboard-extract -elrb-tree-3w" ass.txt

. ass 0 15 "-t -pto-fprtn-and-top-blackboard-extract -estd" ass.txt
. ass 0 15 "-t -pto-fprtn-and-top-blackboard-extract -elrb-tree" ass.txt
. ass 0 15 "-t -pto-fprtn-and-top-blackboard-extract -elrb-tree-3w" ass.txt
#104
