#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$DEBUG_GRAPENLP -ws -a$1 -pbreadth-first -r$2 -o$OUTPUT $WANBN_GRAMMAR $COMPRESSED_DICO
else
$DEBUG_GRAPENLP -ws -a$1 -pbreadth-first -o$OUTPUT $WANBN_GRAMMAR $COMPRESSED_DICO
fi
