#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_NLP -s -pdepth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$DEBUG_NLP -s -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
