#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
	if [ "$1" = "m" ]
	then
		$MTRACE_GRAPENLP -sc -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
	else
		$DEBUG_GRAPENLP -sc -pdepth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
	fi
else
	$DEBUG_GRAPENLP -sc -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
fi
