#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_GRAPENLP -sl -pdepth-first -r$2 $AEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
else
$DEBUG_GRAPENLP -sl -pdepth-first $AEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
fi
