#!/bin/bash
cd `dirname $0`
. paths

echo -n "to_fprtn & breadth-first expand: "
$DEBUG_NLP -xwc $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "to_fprtn & breadth-first expand with trie strings: "
$DEBUG_NLP -xwct $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "earley: "
$DEBUG_NLP -xwc -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "breadth-first: "
$DEBUG_NLP -xwc -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "breadth-first with trie strings: "
$DEBUG_NLP -xwct -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "depth-first: "
$DEBUG_NLP -xwc -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "depth-first with trie strings: "
$DEBUG_NLP -xwct -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
