#!/bin/bash
cd `dirname $0`
. paths

echo -n "to_fprtn & breadth-first expand: "
$DEBUG_GRAPENLP -xw --corpus $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "to_fprtn & breadth-first expand with trie strings: "
$DEBUG_GRAPENLP -xwt --corpus $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "earley: "
$DEBUG_GRAPENLP -xw --corpus -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "breadth-first: "
$DEBUG_GRAPENLP -xw --corpus -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "breadth-first with trie strings: "
$DEBUG_GRAPENLP -xwt --corpus -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "depth-first: "
$DEBUG_GRAPENLP -xw --corpus -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
echo -n "depth-first with trie strings: "
$DEBUG_GRAPENLP -xwt --corpus -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "Validation|Invalid"
