#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_GRAPENLP -sxw --corpus -pearley -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
else
$DEBUG_GRAPENLP -sxw --corpus -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
fi
