#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_NLP -xw -pearley $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$DEBUG_NLP -estd -xw -pearley $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
