#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_GRAPENLP -l -pearley $AEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
else
$DEBUG_GRAPENLP -l -pearley $AEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
fi
