#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
	if [ "$1" = "m" ]
	then
		$MTRACE_GRAPENLP -sxcw -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE
	else
		$DEBUG_GRAPENLP -sxcw -pearley -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE
	fi
else
	$DEBUG_GRAPENLP -sxcw -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE
fi
