#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_GRAPENLP -sxcw -pearley -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
else
$DEBUG_GRAPENLP -sxcw -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
fi
