#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_GRAPENLP -sxwn --corpus -pdepth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT
else
$DEBUG_GRAPENLP -sxwn --corpus -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT
fi
