#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
	if [ "$1" = "m" ]
	then
		$MTRACE_GRAPENLP -sxwn --corpus -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
	else
		$DEBUG_GRAPENLP -sxwn --corpus -pearley -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
	fi
else
	$DEBUG_GRAPENLP -sxwn --corpus -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
fi
