#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_NLP -xwn -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$DEBUG_NLP -xwn -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
