#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_GRAPENLP -sxwtn -pbreadth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $TEST_CONTEXT $OUTPUT
else
$DEBUG_GRAPENLP -sxwtn -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $TEST_CONTEXT $OUTPUT
fi
