#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_GRAPENLP -sxwtn --corpus -pdepth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE
else
$DEBUG_GRAPENLP -sxwtn --corpus -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE
fi
