#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$PROFILE_GRAPENLP -sxw --corpus -pbreadth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
else
$PROFILE_GRAPENLP -sxw --corpus -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
fi
echo \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\# > $BREADTH_FIRST_PROFILE_TRACE
echo \# Breadth-First \# >> $BREADTH_FIRST_PROFILE_TRACE
echo \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\# >> $BREADTH_FIRST_PROFILE_TRACE
echo >> $BREADTH_FIRST_PROFILE_TRACE
gprof $PROFILE_GRAPENLP | $SIMPLIFY_TEMPLATES >> $BREADTH_FIRST_PROFILE_TRACE
vi $BREADTH_FIRST_PROFILE_TRACE
