#!/bin/bash
cd `dirname $0`
. paths

#!/bin/bash
cd `dirname $0`
. ./paths

if [ $# -gt 0 ]
then
$PROFILE_GRAPENLP -sxw --corpus -pearley -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
else
$PROFILE_GRAPENLP -sxw --corpus -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
fi
echo \#\#\#\#\#\#\#\#\#\# > $EARLEY_PROFILE_TRACE
echo \# Earley \# >> $EARLEY_PROFILE_TRACE
echo \#\#\#\#\#\#\#\#\#\# >> $EARLEY_PROFILE_TRACE
echo >> $EARLEY_PROFILE_TRACE
gprof $PROFILE_GRAPENLP | $SIMPLIFY_TEMPLATES >> $EARLEY_PROFILE_TRACE
vi $EARLEY_PROFILE_TRACE
