#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$RELEASE_GRAPENLP -s -a$1 -pbreadth-first -r$2 -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
else
$RELEASE_GRAPENLP -s -a$1 -pbreadth-first -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
fi
