#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$RELEASE_NLP -mxw $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$RELEASE_NLP -xw $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
