#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
	if [ "$1" = "m" ]
	then
		$RELEASE_GRAPENLP -msxw --corpus -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE
	else
		$RELEASE_GRAPENLP -sxw --corpus -pdepth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE
	fi
else
	$RELEASE_GRAPENLP -sxw --corpus -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE
fi
