#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_GRAPENLP -s -pdepth-first -r$2 $AEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
else
$RELEASE_GRAPENLP -s -pdepth-first $AEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
fi
