#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_NLP -sxcwnv -pbreadth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT
else
$RELEASE_NLP -sxcwnv -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT
fi
