#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_GRAPENLP -nsxw --corpus -pearley -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT
else
$RELEASE_GRAPENLP -nsxw --corpus -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT
fi
