#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_NLP -nsxcw -pearley -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT
else
$RELEASE_NLP -nsxcw -pearley $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT
fi
