#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_NLP -sxcwtn -pbreadth-first -r$1 $TID_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE
else
$RELEASE_NLP -sxcwtn -pbreadth-first $TID_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE
fi
