#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_GRAPENLP -sxwtn --corpus -pbreadth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE
else
$RELEASE_GRAPENLP -sxwtn --corpus -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE
fi
