#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_GRAPENLP -sxcwtn -pdepth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
else
$RELEASE_GRAPENLP -sxcwtn -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
fi
