#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_NLP -sxcwt -pbreadth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
else
$RELEASE_NLP -sxcwt -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
fi
