#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_GRAPENLP -sxwt --corpus -pbreadth-first -r$1 $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
else
$RELEASE_GRAPENLP -sxwt --corpus -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
fi
