#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_NLP -sxcwt -r$1 $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
else
$RELEASE_NLP -sxcwt $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
fi
