#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$RELEASE_NLP -st -a$1 -pdepth-first -r$2 -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
else
$RELEASE_NLP -st -a$1 -pdepth-first -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
fi
