#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$RELEASE_GRAPENLP -st -a$1 -pearley -r$2 -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
else
$RELEASE_GRAPENLP -st -a$1 -pearley -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
fi
