#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_GRAPENLP -sxw --corpus -r$1 -pto-fprtn-and-breadth-first-expand $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
else
$RELEASE_GRAPENLP -sxw --corpus -pto-fprtn-and-breadth-first-expand $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT
fi
