#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
	if [ "$1" = "m" ]
	then
		$RELEASE_NLP -msxcw -pto-fprtn-and-top-blackboard-extract $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE
	else
		$RELEASE_NLP -sxcw -r$1 -pto-fprtn-and-top-blackboard-extract $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE
	fi
else
	$RELEASE_NLP -sxcw -pto-fprtn-and-top-blackboard-extract $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE
fi
