#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$RELEASE_GRAPENLP -wst -a$1 -r$2 -pto-fprtn-and-breadth-first-expand -o$OUTPUT $WANBN_GRAMMAR $COMPRESSED_DICO
else
$RELEASE_GRAPENLP -wst -a$1 -pto-fprtn-and-breadth-first-expand -o$OUTPUT $WANBN_GRAMMAR $COMPRESSED_DICO
fi
