#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
	if [ "$1" = "m" ]
	then
		$RELEASE_GRAPENLP -msxwt --corpus -pto-fprtn-and-blackboard-set-expand -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE
	else
		$RELEASE_GRAPENLP -sxwt --corpus -r$1 -pto-fprtn-and-blackboard-set-expand -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE
	fi
else
	$RELEASE_GRAPENLP -sxw --corpus -pto-fprtn-and-blackboard-set-expand -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE
fi
