#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_NLP -sxwt -r$1 -pto-fprtn-and-blackboard-set-expand $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$RELEASE_NLP -sxwt -pto-fprtn-and-blackboard-set-expand $TID_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
