#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$RELEASE_GRAPENLP -sxwt -r$1 -pto-fprtn-and-top-blackboard-extract $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$RELEASE_GRAPENLP -sxwt -pto-fprtn-and-top-blackboard-extract $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
