#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$RELEASE_NLP -st -a$1 -r$2 -pto-fprtn-and-blackboard-set-expand -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
else
$RELEASE_NLP -st -a$1 -pto-fprtn-and-blackboard-set-expand -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
fi
