#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$DEBUG_NLP --desc-parser -st -a$1 -pbreadth-first -r$2 -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
else
$DEBUG_NLP --desc-parser -st -a$1 -pbreadth-first -estd -bstd -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
fi
