#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_NLP -sxcwt -pbreadth-first -r$1 $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
else
$DEBUG_NLP -sxcwt -pbreadth-first $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT
fi
