#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_GRAPENLP -xwt -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $TEST_CONTEXT $OUTPUT
else
$DEBUG_GRAPENLP -xwt -pbreadth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $TEST_CONTEXT $OUTPUT
fi
