#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
	if [ "$1" = "m" ]
	then
		$MTRACE_NLP -sxcwt $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE
	else
		$DEBUG_NLP -sxcwt -r$1 $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE
	fi
else
	$DEBUG_NLP -sxcwt $TID_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE
fi
