#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$DEBUG_GRAPENLP -tws -a$1 -pdepth-first -r$2 -o$OUTPUT $WANBN_GRAMMAR $COMPRESSED_DICO
else
$DEBUG_GRAPENLP -tws -a$1 -pdepth-first -o$OUTPUT $WANBN_GRAMMAR $COMPRESSED_DICO
fi
