#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$DEBUG_GRAPENLP --desc-parser -st -a$1 -pdepth-first -r$2 -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
else
$DEBUG_GRAPENLP --desc-parser -st -a$1 -pdepth-first -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
fi
