#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_NLP --desc -l -pto-fprtn-and-blackboard-set-expand $AEEE_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$DEBUG_NLP --desc -l -pto-fprtn-and-blackboard-set-expand $AEEE_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
