#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$DEBUG_NLP -s -a$1 -r$2 -pto-fprtn-zpps -elrb-tree -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
else
$DEBUG_NLP -s -a$1 -pto-fprtn-zpps -elrb-tree -o$OUTPUT $ANBN_GRAMMAR $COMPRESSED_DICO
fi
