#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_GRAPENLP -xw -pto-fprtn-and-top-blackboard-extract $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $TEST_CONTEXT $OUTPUT
else
$DEBUG_GRAPENLP -xw -pto-fprtn-and-top-blackboard-extract $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $TEST_CONTEXT $OUTPUT
fi
