#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 1 ]
then
$DEBUG_NLP -sw -a$1 -r$2 -pto-fprtn-and-top-blackboard-extract -o$OUTPUT $WANBN_GRAMMAR $COMPRESSED_DICO
else
$DEBUG_NLP -sw -a$1 -pto-fprtn-and-top-blackboard-extract -o$OUTPUT $WANBN_GRAMMAR $COMPRESSED_DICO
fi
