#!/bin/bash
cd `dirname $0`
. paths

if [ $# -gt 0 ]
then
$DEBUG_GRAPENLP -sxcw -r$1 -pto-fprtn-and-breadth-first-expand $CHATBOT_GRAMMAR $TEXT_DICO $CORPUS $OUTPUT $VALIDATE
else
$DEBUG_GRAPENLP -sxcw -pto-fprtn-and-breadth-first-expand $CHATBOT_GRAMMAR $TEXT_DICO $CORPUS $OUTPUT $VALIDATE
fi
