#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_GRAPENLP --desc -l -pto-fprtn-and-blackboard-set-expand $AEEE_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $TEST_CONTEXT $OUTPUT
else
$DEBUG_GRAPENLP --desc -l -pto-fprtn-and-blackboard-set-expand $AEEE_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $TEST_CONTEXT $OUTPUT
fi
