#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_NLP --desc -lwt -pto-fprtn-and-top-blackboard-extract $WAEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
else
$DEBUG_NLP --desc -lwt -pto-fprtn-and-top-blackboard-extract $WAEEE_GRAMMAR $COMPRESSED_DICO $A_INPUT $OUTPUT
fi
