#!/bin/bash
cd `dirname $0`
. paths

if [ "$1" = "m" ]
then
$MTRACE_NLP -xwt -pto-fprtn-and-top-blackboard-extract $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
else
$DEBUG_NLP -xwt -pto-fprtn-and-top-blackboard-extract $CHATBOT_GRAMMAR $COMPRESSED_DICO $TEST_INPUT $OUTPUT
fi
