#!/bin/bash

GRAPENLP_EXECUTABLE="$1"

#To-FPRTN & top blackboard extraction
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-top-blackboard-extract -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-top-blackboard-extract -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-top-blackboard-extract -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-top-blackboard-extract -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-top-blackboard-extract -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-top-blackboard-extract -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-top-blackboard-extract -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-top-blackboard-extract -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-top-blackboard-extract -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#To-FPRTN & blackboard-set expansion
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-blackboard-set-expand -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-blackboard-set-expand -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-blackboard-set-expand -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-blackboard-set-expand -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#To-FPRTN & breadth-first expansion
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-breadth-first-expand -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pto-fprtn-and-breadth-first-expand -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-breadth-first-expand -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pto-fprtn-and-breadth-first-expand -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-breadth-first-expand -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pto-fprtn-and-breadth-first-expand -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Earley
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pearley -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pearley -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pearley -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pearley -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pearley -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pearley -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pearley -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pearley -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pearley -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Earley no output
$GRAPENLP_EXECUTABLE --desc-parser -nxw --corpus -pearley -estd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -nxw --corpus -pearley -elrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -nxw --corpus -pearley -elrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Breadth-first
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pbreadth-first -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pbreadth-first -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pbreadth-first -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pbreadth-first -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pbreadth-first -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pbreadth-first -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pbreadth-first -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pbreadth-first -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pbreadth-first -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pbreadth-first -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pbreadth-first -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pbreadth-first -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pbreadth-first -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pbreadth-first -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pbreadth-first -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pbreadth-first -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pbreadth-first -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pbreadth-first -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Breadth-first no output
$GRAPENLP_EXECUTABLE --desc-parser -nxw --corpus -pbreadth-first -estd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -nxwt --corpus -pbreadth-first -estd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -nxw --corpus -pbreadth-first -elrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -nxwt --corpus -pbreadth-first -elrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -nxw --corpus -pbreadth-first -elrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -nxwt --corpus -pbreadth-first -elrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Top-down
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pdepth-first -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pdepth-first -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pdepth-first -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pdepth-first -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xw --corpus -pdepth-first -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -xwt --corpus -pdepth-first -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Top-down no output
$GRAPENLP_EXECUTABLE --desc-parser -nxw --corpus -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$GRAPENLP_EXECUTABLE --desc-parser -nxwt --corpus -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $TEST_CONTEXT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
