#!/bin/bash
cd `dirname $0`
. paths

#To-FPRTN & top blackboard extraction
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-top-blackboard-extract -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-top-blackboard-extract -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-top-blackboard-extract -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-top-blackboard-extract -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-top-blackboard-extract -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-top-blackboard-extract -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-top-blackboard-extract -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-top-blackboard-extract -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-top-blackboard-extract -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#To-FPRTN & blackboard-set expansion
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-blackboard-set-expand -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-blackboard-set-expand -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-blackboard-set-expand -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-blackboard-set-expand -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-blackboard-set-expand -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-blackboard-set-expand -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#To-FPRTN & breadth-first expansion
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-breadth-first-expand -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pto-fprtn-and-breadth-first-expand -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g' | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-breadth-first-expand -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pto-fprtn-and-breadth-first-expand -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g' | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-breadth-first-expand -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pto-fprtn-and-breadth-first-expand -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g' | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-breadth-first-expand -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pto-fprtn-and-breadth-first-expand -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pto-fprtn-and-breadth-first-expand -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pto-fprtn-and-breadth-first-expand -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Earley
$RELEASE_GRAPENLP --desc-parser -xwc -pearley -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pearley -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pearley -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pearley -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pearley -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pearley -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pearley -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pearley -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pearley -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Earley no output
$RELEASE_GRAPENLP --desc-parser -nxwc -pearley -estd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -nxwc -pearley -elrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -nxwc -pearley -elrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Breadth-first
$RELEASE_GRAPENLP --desc-parser -xwc -pbreadth-first -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pbreadth-first -estd -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pbreadth-first -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pbreadth-first -estd -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pbreadth-first -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pbreadth-first -estd -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pbreadth-first -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pbreadth-first -elrb-tree -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pbreadth-first -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pbreadth-first -elrb-tree -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pbreadth-first -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pbreadth-first -elrb-tree -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pbreadth-first -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pbreadth-first -elrb-tree-3w -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pbreadth-first -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pbreadth-first -elrb-tree-3w -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pbreadth-first -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pbreadth-first -elrb-tree-3w -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Breadth-first no output
$RELEASE_GRAPENLP --desc-parser -nxwc -pbreadth-first -estd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -nxwct -pbreadth-first -estd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -nxwc -pbreadth-first -elrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -nxwct -pbreadth-first -elrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -nxwc -pbreadth-first -elrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -nxwct -pbreadth-first -elrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Top-down
$RELEASE_GRAPENLP --desc-parser -xwc -pdepth-first -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pdepth-first -bstd $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pdepth-first -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pdepth-first -blrb-tree $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwc -pdepth-first -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -xwct -pdepth-first -blrb-tree-3w $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'

#Top-down no output
$RELEASE_GRAPENLP --desc-parser -nxwc -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
$RELEASE_GRAPENLP --desc-parser -nxwct -pdepth-first $CHATBOT_GRAMMAR $COMPRESSED_DICO $CORPUS_NO_OUTPUT $OUTPUT $VALIDATE | grep -E "\*\ |Validation|Invalid|fault" | sed 's/.*\*\ //g' | sed 's/\ \*.*//g'
