/*
 * GRAPENLP
 *
 * Copyright (C) 2004-2021 Javier Miguel Sastre Martínez <javier.sastre@univ-mlv.fr>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
 *
 */

/*
 *  @author Javier Sastre
 */

package com.grapenlp;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.TreeSet;

public class ToLowercaseTableHeaderWriter implements WriterConstants
{
    public void write(TreeSet<CaseFoldingEntry> entries, File toLowercaseTableHeaderFile, boolean verbose) throws IOException {
        int[] caseTable = new int[MAX_LETTERS];
        int i;
        for (i = 0; i < MAX_LETTERS; ++i)
            caseTable[i] = i;

        for (CaseFoldingEntry entry: entries)
        {
            caseTable[entry.getLowerCaseCode()] = entry.getCanonicalForm().getLowerCaseCode();
            caseTable[entry.getUpperCaseCode()] = entry.getCanonicalForm().getLowerCaseCode();
        }

        try (BufferedWriter output = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(toLowercaseTableHeaderFile), StandardCharsets.UTF_8)))
        {
            output.write(license);
            output.write('\n');
            output.write(autogenerated);
            output.write('\n');
            output.write("#ifndef GRAPENLP_U_TO_LOWERCASE_TABLE_H\n");
            output.write("#define GRAPENLP_U_TO_LOWERCASE_TABLE_H\n");
            output.write("\n");
            output.write("#include <grapenlp/unichar.h>\n");
            output.write("\n");
            output.write("namespace grapenlp\n");
            output.write("{\n");
            output.write("    const unichar u_tolowercase_table[] = {\n");

            if (verbose)
            {
                System.out.println("To lowercase table:");
                for (i = 32; i < MAX_LETTERS; ++i)
                    if (i != caseTable[i])
                        System.out.println("(" + Integer.toString(i, 16) + ":" + Integer.toString(caseTable[i], 16) + ") (" + ((char)i) + ":" + ((char)caseTable[i]) + ")");
            }

            //Non printable characters
            for (i = 0; i < 32; ++i)
                output.write("         " + Integer.toString(caseTable[i]) + ",\n");
            int max_letters_minus_one = MAX_LETTERS - 1;
            //Printable characters
            for (; i < max_letters_minus_one; ++i)
                output.write("         " + Integer.toString(caseTable[i]) + ", // (" + Integer.toString(i, 16) + ":" + Integer.toString(caseTable[i], 16) + ") (" + ((char)i) + ":" + ((char)caseTable[i]) + ")\n");
            output.write("         " + Integer.toString(caseTable[i]) + " // (" + Integer.toString(i, 16) + ":" + Integer.toString(caseTable[i], 16) + ") (" + ((char)i) + ":" + ((char)caseTable[i]) + ")\n");
            output.write("    };\n");
            output.write("} //namespace grapenlp\n");
            output.write("\n");
            output.write("#endif //GRAPENLP_U_TO_LOWERCASE_TABLE_H\n");
        }
    }
}
